### ISSUE TITLE
Copying

### ISSUE THREAD

**Issue by Aspie96** [halcy/AnimeFaceNotebooks#1]
Hi!
This is nice.

Would you consider providing a license for others to use?

**Comment by halcy** [comment]
Adressed.

**Comment by Aspie96** [comment]
Thanks!
Given that the repo contains works from others (such as NVlabs, nonfree), this should be specified.

Would you like me to try adding a "license" section to specify this so it's clear for others?

**Comment by halcy** [comment]
It just references them as subrepos, and they have their own license files
in there, but sure, why not, can't hurt.

**Comment by Aspie96** [comment]
The reason it's important is that the code from NVidia is actually proprietary (it is NOT open source). If somebody, for instance, embeds your code into a GPL code from others because they see "MIT", they would break the GPL license and be in trouble

**Comment by halcy** [comment]
well, not really no. This repository does not contain any code written by anyone other than me. While it does have the stylegan and deepdanbooru repositories as submodules, submodules are effectively symbolic links. If you redistribute only this repo, you will not redistribute any code from nvidia or from kanotype, just mine - you'll get the rest of the code straight from the source repositories (and both the MIT license and nvidias license are open source licenses, the latter just has a few usage restrictions, mostly that you can't use it in commercial software, which makes it, to the fsf, non-free)

As for the code itself, it does _use_ the stylegan code (and deepdanbooru code), but using a module is linking. Linking a not gold-star-libre-free-software library from a free software library will make the fsf make a frowny face at you, but it isn't a legal issue per se (though if someone does it with my code, they _may_ have to ask me first - not sure how that works exactly).

In any case, even if someone did relicense this code under the GPL (which, frankly, would be sort of a weird thing to do - adding the additional restrictions that the GPL has on top of other code that the author chose to license permissively and preventing, in theory, code from going back upstream is a bit ? ? ?), for a potential GPL violation to matter, that person would have to file some sort of civil complaint against somebody else redistributing that code, which seems unlikely.

All that said: Putting a short note who wrote the software and weights is probably a good idea, if not just good form, and I've done as much.

**Comment by Aspie96** [comment]
I am not concearned about the FSF, I don't even agree with them to be honest.

I was imagining the following scenario: somebody releases library X under a copyleft license, such as the GPL.
Somebody ELSE sees a library under MIT (such as one derived from your code) and uses it together with library X.

If they do so, they now have a program with a proprietary dependency, this isn't allowed by the license of library X, even if it's just linking it.

**Comment by halcy** [comment]
If that person does that and distributes their code (under the GPL, since they're using a GPL library), they can do that just fine - they just have to add a short notice to allow everybody else to also link that piece of GPL code agains the "non-free" library ( https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs ).

Even if you could not, or forgot to put that "yes, I actually meant to do this and you are also allowed to" paragraph: If I put a license on my code, I'm doing it wrong, and the license is actually invalid, it just means that everything reverts to the default of "no license, all rights reserved", and I can always go "my b. you can use it under (other license) from now on, actually."

Sure, it is possible to end up with some large licensing mess if people use code backwards and forwards a lot, but that's not likely - and in any case, there's now a note, so even if somebody doesn't do their due diligence, they should presumably see.
